# MakeNL makefile for macOS 10 & later
# Tested with GNU Make 3.81 & clang-1000.11.45.5 on macOS 10.14.5
#
# Build with:
#
# make -f makefile.macos          (release) or
# make -f makefile.macos DEBUG=1  (debug)
# make -f makefile.macos clean    (remove temp files)
# make -f makefile.macos CC=clang (build with clang)
# make -f makefile.macos ASAN=1   (debug build with clang using AddressSanitizer)

CC=cc
CFLAGS+= -Wall -W

ifdef ASAN
CC=clang
CFLAGS+= -g -fsanitize=address -fno-omit-frame-pointer
endif

ifdef DEBUG
CFLAGS+= -g
endif

ifdef TESTING
CFLAGS+= -DTESTING
OBJS+=testing.o
endif

OBJS+=config.o crc16.o fileutil.o fts5.o lsttool.o makenl.o merge.o
OBJS+=mkdiff.o mklog.o msgtool.o os.o output.o procfile.o stack.o
OBJS+=strtool.o upcont.o

.c.o:
	$(CC) $(CFLAGS) -c $<

makenl: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS) $(LDFLAGS)

clean:
	rm -f $(OBJS) makenl
